services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile.prod
    container_name: gql-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.prod
    container_name: next-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
