services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: gql-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./back:/app
    working_dir: /app
    command: go run server.go

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: next-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
    working_dir: /app
    command: pnpm dev
    env_file:
      - .env
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
